### POST request to products server
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Carrot",
  "price": 2.99,
  "vendorId": "c8ab11e3-6efa-4412-951e-fd2b3810e7c1"
}

### POST request to service server
POST http://localhost:8080/services
Content-Type: application/json

{
  "name": "Delivery",
  "price": 5.99
}

### GET request to customers server with query parameter id
GET http://localhost:8080/customers?id=6bb56738-20d6-4a7b-9362-1416fd35fd10


